server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${SPRING_DATASOURCE_USERNAME:orders}
    password: ${SPRING_DATASOURCE_PASSWORD:orders}

  jpa:
    hibernate:
      ddl-auto: validate   # schema harus sudah ada dari SQL migration
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true

  flyway:
    enabled: false         # tetap false, kamu jalankan SQL manual via pgAdmin
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug

payments:
  base-url: ${PAYMENTS_BASE_URL:http://localhost:8082}

jwt:
  secret: "ganti-ini-dengan-string-yang-lebih-panjang-dan-acak-ya-1234567890"
  expiration-seconds: 3600
